const QuranData = {
  surahNames: [
    { id: 1, nameEnglish: "Al-Fatiha", nameArabic: "الفاتحة" },
    { id: 2, nameEnglish: "Al-Baqarah", nameArabic: "البقرة" },
    { id: 3, nameEnglish: "Al-Imran", nameArabic: "آل عمران" },
    { id: 4, nameEnglish: "An-Nisa", nameArabic: "النساء" },
    { id: 5, nameEnglish: "Al-Ma'idah", nameArabic: "المائدة" },
    { id: 6, nameEnglish: "Al-An'am", nameArabic: "الأنعام" },
    { id: 7, nameEnglish: "Al-A'raf", nameArabic: "الأعراف" },
    { id: 8, nameEnglish: "Al-Anfal", nameArabic: "الأنفال" },
    { id: 9, nameEnglish: "At-Tawbah", nameArabic: "التوبة" },
    { id: 10, nameEnglish: "Yunus", nameArabic: "يونس" },
    { id: 11, nameEnglish: "Hud", nameArabic: "هود" },
    { id: 12, nameEnglish: "Yusuf", nameArabic: "يوسف" },
    { id: 13, nameEnglish: "Ar-Ra'd", nameArabic: "الرعد" },
    { id: 14, nameEnglish: "Ibrahim", nameArabic: "إبراهيم" },
    { id: 15, nameEnglish: "Al-Hijr", nameArabic: "الحجر" },
    { id: 16, nameEnglish: "An-Nahl", nameArabic: "النحل" },
    { id: 17, nameEnglish: "Al-Isra", nameArabic: "الإسراء" },
    { id: 18, nameEnglish: "Al-Kahf", nameArabic: "الكهف" },
    { id: 19, nameEnglish: "Maryam", nameArabic: "مريم" },
    { id: 20, nameEnglish: "Ta-Ha", nameArabic: "طه" },
    { id: 21, nameEnglish: "Al-Anbiya", nameArabic: "الأنبياء" },
    { id: 22, nameEnglish: "Al-Hajj", nameArabic: "الحج" },
    { id: 23, nameEnglish: "Al-Mu'minun", nameArabic: "المؤمنون" },
    { id: 24, nameEnglish: "An-Nur", nameArabic: "النور" },
    { id: 25, nameEnglish: "Al-Furqan", nameArabic: "الفرقان" },
    { id: 26, nameEnglish: "Ash-Shu'ara", nameArabic: "الشعراء" },
    { id: 27, nameEnglish: "An-Naml", nameArabic: "النمل" },
    { id: 28, nameEnglish: "Al-Qasas", nameArabic: "القصص" },
    { id: 29, nameEnglish: "Al-Ankabut", nameArabic: "العنكبوت" },
    { id: 30, nameEnglish: "Ar-Rum", nameArabic: "الروم" },
    // Add more surah names here
  ],
  juzzNames: [
    { id: 1, nameEnglish: "Juzz 1", nameArabic: "الجزء الأول" },
    { id: 2, nameEnglish: "Juzz 2", nameArabic: "الجزء الثاني" },
    { id: 3, nameEnglish: "Juzz 3", nameArabic: "الجزء الثالث" },
    { id: 4, nameEnglish: "Juzz 4", nameArabic: "الجزء الرابع" },
    { id: 5, nameEnglish: "Juzz 5", nameArabic: "الجزء الخامس" },
    { id: 6, nameEnglish: "Juzz 6", nameArabic: "الجزء السادس" },
    { id: 7, nameEnglish: "Juzz 7", nameArabic: "الجزء السابع" },
    { id: 8, nameEnglish: "Juzz 8", nameArabic: "الجزء الثامن" },
    { id: 9, nameEnglish: "Juzz 9", nameArabic: "الجزء التاسع" },
    { id: 10, nameEnglish: "Juzz 10", nameArabic: "الجزء العاشر" },
    { id: 11, nameEnglish: "Juzz 11", nameArabic: "الجزء الحادي عشر" },
    { id: 12, nameEnglish: "Juzz 12", nameArabic: "الجزء الثاني عشر" },
    { id: 13, nameEnglish: "Juzz 13", nameArabic: "الجزء الثالث عشر" },
    { id: 14, nameEnglish: "Juzz 14", nameArabic: "الجزء الرابع عشر" },
    { id: 15, nameEnglish: "Juzz 15", nameArabic: "الجزء الخامس عشر" },
    { id: 16, nameEnglish: "Juzz 16", nameArabic: "الجزء السادس عشر" },
    { id: 17, nameEnglish: "Juzz 17", nameArabic: "الجزء السابع عشر" },
    { id: 18, nameEnglish: "Juzz 18", nameArabic: "الجزء الثامن عشر" },
    { id: 19, nameEnglish: "Juzz 19", nameArabic: "الجزء التاسع عشر" },
    { id: 20, nameEnglish: "Juzz 20", nameArabic: "الجزء العشرون" },
    { id: 21, nameEnglish: "Juzz 21", nameArabic: "الجزء الواحد و العشرون" },
    { id: 22, nameEnglish: "Juzz 22", nameArabic: "الجزء الثاني و العشرون" },
    { id: 23, nameEnglish: "Juzz 23", nameArabic: "الجزء الثالث و العشرون" },
    { id: 24, nameEnglish: "Juzz 24", nameArabic: "الجزء الرابع و العشرون" },
    { id: 25, nameEnglish: "Juzz 25", nameArabic: "الجزء الخامس و العشرون" },
    { id: 26, nameEnglish: "Juzz 26", nameArabic: "الجزء السادس و العشرون" },
    { id: 27, nameEnglish: "Juzz 27", nameArabic: "الجزء السابع و العشرون" },
    { id: 28, nameEnglish: "Juzz 28", nameArabic: "الجزء الثامن و العشرون" },
    { id: 29, nameEnglish: "Juzz 29", nameArabic: "الجزء التاسع و العشرون" },
    { id: 30, nameEnglish: "Juzz 30", nameArabic: "الجزء الثلاثون" },
  ],
};

export default QuranData;
